### PR TITLE
Enable add/delete on right-click menu

### PR DESCRIPTION
**Pull request by jrowen**
This update adds functionality to support adding and deleting columns and rows via the right-click context menu.

### CODE REVIEW

**Comment by trestletech** [comment]
Thanks for doing this; this one's going to take me a little longer to review, but I'll keep you posted as I have questions. Let me know if merging this is blocking you and I'll see what I can do to speed up the process.

**Comment by trestletech** [comment]
When running sample-01 in Chrome, if I right-click the "40" cell and select "remove row", I get a slew of JS errors in the console. It looks like there's an issue recomputing the cellClasses object that would dictate the formatting for the revised table that now has a different number of rows/cells.

Honestly now that I look at that original code, though, I can see a dozen ways to improve it. I might consider refactoring some of that myself before you make your PR compatible. So I'll just note that here as a TODO, but don't spend much time on it until I can confirm that I'm not going to rip that part out anyways.

**Comment by trestletech** [comment]
I've just been testing with the 01-simple example and I'm seeing a few problems. I added a `print(tbl)` before returning in the server on line 45 and I'm seeing some strange issues with how the table gets rendered. In particular, when adding a column, the column names all get messed up and I get JS errors on the client. I'm not sure this one has to do with the cell formatting. Can you take a look and make sure your code is behaving as you expect for the sample?

Thanks

**Comment by jrowen** [comment]
I fixed the column and row names as well as the javascript errors.  I'm not sure if the cell shading is working with the context menu.  I see the cell format updates when debugging, but the final table doesn't appear to keep the format updates.

If you decide to refactor the code, it may be possible to do a lot of this more efficiently.  I'm not sure the `htmlwidgets` package could be an option, although I'm not sure if it supports input binding.

**Comment by jrowen** [comment]
@trestletech I made an attempt at porting this functionality to the `htmlwidgets` framework and would appreciate your thoughts/suggestions/contributions on the new library [`rhandsontable`](https://github.com/jrowen/rhandsontable).

For now it uses `Shiny.onInputChange` to pass input to the server, which doesn't have all the functionality of an input binding but still seems to be effective.  The `htmlwidgets` framework also makes it easier to implement additional handsontable functionality.

**Comment by trestletech** [comment]
Sorry that I haven't had more time to give to this package. Is it safe to say that your new package includes all of the functionality you suggest in this PR? (Thanks for doing all that work, btw -- sorry I couldn't be more responsive). 

If your package offers this functionality, I can add a link to my README to recommend that people check yours out which perhaps will be better maintained. Or if this PR is orthogonal I can try to find time to take a look at it for this package.

**Comment by jrowen** [comment]
The new version does include all of this functionality, so from my
perspective, there's no longer a need to merge this PR.

I figured you'd moved on to some more interesting projects (I'm very
interested to try out the R API), and the htmlwidgets package made it
really easy to port this and more of the Handsontable functionality to R.
Feel free to include a link in the shinyTable readme, and I'd be happy to
add you as a project author on github if you'd like.  Thanks for all of the
initial work.

**Pull request closed without merging**
